### ISSUE TITLE
Your scripts are Amazing and always impressed me !

### ISSUE THREAD

**Issue by fossimprove** [Sidmaz666/streamo#2]
I love you have fzf and rofi to use as menu, and it makes it a fantastic use case for me.
I mainly discovered your script by searching for manga-cli on github.
Am very grateful to have found your channel.

I suggest you to showcase your scripts in r/unixporn you will attract alot of CLI fans out there.
Just name it [OC] and demo the script, sure it will pop over the subreddit and you will get lots of contributors too.

I can understand if you dont want to gather alot of audience or fall into trouble by incresed user.

Im just thankful for your scripts!

**Comment by fossimprove** [comment]
Also in r/linux 
r/commandline
r/linuxmasterace

And things will spread out.

**Comment by Sidmaz666** [comment]
Thank you very much, I'm very glad that my scripts are helpful to people. 
I have showcase my scripts before in a discord server unixporn, I don't think it have reach out to many people. Showcasing in Reddit is a good idea indeed. I will try to post, if you don't see my post you can go ahead if you want to and showcase my scripts. Once, again Thank you very much for taking out your time and reach me.
